// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igstbnsgpquovtuuhgqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnc3RibnNncHF1b3Z0dXVoZ3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzUzMDYsImV4cCI6MjA2NTcxMTMwNn0.S-rHqlFas87xHVRzEfdheor9BylWd_iQHdfO3M8iSZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);